name: Fail Demo
on: [push]

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This job will fail intentionally"
      - name: Force failure
        run: exit 1
